ucbepic/docetl

- docetl/api.py
> Add a save config method to the Python API

- README.md
> Add podcast to readme

- docs/operators/resolve.md
> docs: fix resolve docs

- docs/examples/ollama.md
- docs/tutorial.md
> docs: link to ollama chat

- Makefile
- docetl/api.py
- docetl/builder.py
- docetl/dataset.py
- docetl/operations/utils.py
- docetl/parsing_tools.py
- docetl/runner.py
- docetl/schemas.py
- docs/api-reference/python.md
- docs/concepts/pipelines.md
- docs/examples/custom-parsing.md
- docs/examples/ollama.md
- docs/python-api.md
- docs/tutorial.md
- mkdocs.yml
- poetry.lock
- pyproject.toml
- tests/basic/sample_texts/one.txt
- tests/basic/sample_texts/two.md
- tests/basic/test_pipeline_with_parsing.py
- tests/test_parsing_tools.py
Addresses #2 and closes #11
This PR introduces a new `Dataset` class and associated parsing tools to enhance our data handling capabilities. 
Parsing tools are functions that process specific fields in the dataset. Each parsing tool is defined with:
- `input_key`: The key in the dataset to which the parsing function will be applied.
- `function`: The name of the parsing function to use.
- `output_key`: The key where the parsed result will be stored.
For example:
```python
from docetl.api import Pipeline, Dataset, ParsingTool
custom_parser = ParsingTool(
name="custom_txt_parser",
function_code="def custom_txt_parser(text): return text.upper()"
)
pipeline = Pipeline(
datasets={
"input_data": Dataset(
type="file",
source="local",
path="input.json",
parsing=[
{
"input_key": "text", …
```
>  Add Dataset Class and Parsing Tools

- docs/examples/custom-parsing.md
> docs: improve clarity for custom parsing

- docetl/operations/filter.py
- docetl/operations/map.py
- docetl/operations/utils.py
Closes #50  -- thanks @redhog!
> fix: dont cache results of bad llm calls

- docetl/parsing_tools.py
- pyproject.toml
Closes https://github.com/ucbepic/docetl/issues/51
> Added llama-index based parsers

- docetl/parsing_tools.py
- tests/test_parsing_tools.py
This PR is closely related to #3 . It uses openai API to convert pdf to md files.
I tested it using [this_pdf](https://github.com/fraponyo94/Text-Extraction-Scanned-Pdf/blob/master/sample-scanned-pdfs/PublicWaterMassMailing.pdf) and here are the [results.](https://github.com/user-attachments/files/17265380/output_md.md)
> feat: add pdfgpt to parse PDFs

- docetl/parsing_tools.py
- tests/test_parsing_tools.py
> Merging staging to main (from add gpt_pdf)

- .github/workflows/stage.yml
- docetl/operations/utils.py
- docetl/parsing_tools.py
- pyproject.toml
- tests/test_parsing_tools.py
As title--to address a bug flagged in discord
> fix: disable additional properties for gemini

- docetl/operations/map.py
- docetl/operations/reduce.py
- docetl/operations/utils.py
- docetl/optimizers/reduce_optimizer.py
- tests/test_api.py
> feat: add verbose parameter for gleaning

- docs/operators/filter.md
- docs/operators/gather.md
- docs/operators/map.md
- docs/operators/parallel-map.md
- docs/operators/reduce.md
- docs/operators/resolve.md
- docs/operators/split.md
- docs/operators/unnest.md
> docs: add sample parameter

- docetl/api.py
- docetl/operations/cluster.py
- docetl/operations/map.py
- docetl/operations/reduce.py
- docetl/operations/split.py
- docetl/operations/utils.py
- docetl/optimizers/reduce_optimizer.py
- docetl/runner.py
- docetl/utils.py
- docs/api-reference/operations.md
- docs/concepts/operators.md
- docs/examples/custom-parsing.md
- docs/examples/rate-limiting.md
- docs/operators/cluster.md
- docs/operators/filter.md
- docs/operators/gather.md
- docs/operators/map.md
- docs/operators/parallel-map.md
- docs/operators/reduce.md
- docs/operators/resolve.md
- docs/operators/split.md
- docs/operators/unnest.md
- mkdocs.yml
- poetry.lock
- pyproject.toml
- tests/basic/test_cluster.py
- tests/basic/test_pipeline_with_parsing.py
- tests/test_api.py
- tests/test_validation.py
> feat: output to csv if user specifies a csv file

- docetl/operations/cluster.py
- docetl/operations/equijoin.py
- docetl/operations/filter.py
- docetl/operations/map.py
- docetl/operations/reduce.py
- docetl/operations/resolve.py
- docetl/operations/utils.py
- tests/basic/test_basic_filter_split_gather.py
- tests/basic/test_basic_map.py
- tests/basic/test_basic_parallel_map.py
- tests/basic/test_basic_reduce_resolve.py
- tests/basic/test_cluster.py
- tests/conftest.py
- tests/test_api.py
- tests/test_eugene.py
- tests/test_reduce_scale.py
- tests/test_validation.py
> refactor: move validation and gleaning into call llm

- docetl/operations/reduce.py
- docs/operators/reduce.md
- tests/basic/test_basic_reduce_resolve.py
> feat: add reduce operation lineage

- docs/api-reference/python.md
> docs: add sample and cluster to docs

- docs/api-reference/python.md
> fix: make docs work

- docetl/optimizers/map_optimizer/optimizer.py
- docetl/optimizers/map_optimizer/plan_generators.py
- docetl/optimizers/map_optimizer/prompt_generators.py
- docetl/optimizers/map_optimizer/utils.py
> feat: adding human in the loop for split-map-gather decomp

- tests/basic/test_basic_map.py
> mark as flaky test

- docetl/operations/resolve.py
Previously, we were comparing all pairs in resolve that passed blocking conditions, regardless of whether there were duplicate pairs. This PR only compares duplicates.
> only compare distinct pairs in resolve

- docetl/operations/link_resolve.py
- docs/operators/link-resolve.md
- pyproject.toml
Closes https://github.com/ucbepic/docetl/issues/108
> LinkResolveOperation

- docetl/__init__.py
- docs/operators/resolve.md
- pyproject.toml
- tests/basic/test_pipeline_with_parsing.py
> Merge auto batching PR

- docs/operators/filter.md
> docs: link filter to map

- docetl/runner.py
> fix: only call os makedirs on non empty paths

- docetl/operations/utils.py
- website/src/app/api/utils.ts
- website/src/app/api/writePipelineConfig/route.ts
- website/src/components/PipelineGui.tsx
> fix: clear and run button should also bypass cache

- docetl/operations/code_operations.py
- docs/operators/code.md
- mkdocs.yml
- pyproject.toml
- tests/basic/test_code_operations.py
> Merge staging into MAIN

- README.md
- docetl/builder.py
- docetl/console.py
- docetl/operations/base.py
- docetl/optimizers/join_optimizer.py
- docetl/optimizers/map_optimizer/config_generators.py
- docetl/optimizers/map_optimizer/evaluator.py
- docetl/optimizers/map_optimizer/optimizer.py
- docetl/optimizers/map_optimizer/plan_generators.py
- docetl/optimizers/map_optimizer/prompt_generators.py
- docetl/optimizers/reduce_optimizer.py
- docetl/runner.py
- docetl/utils.py
- server/app/routes/pipeline.py
- website/package-lock.json
- website/package.json
- website/src/app/api/utils.ts
- website/src/app/localStorageKeys.ts
- website/src/app/types.ts
- website/src/components/AnsiRenderer.tsx
- website/src/components/OperationCard.tsx
- website/src/components/Output.tsx
- website/src/components/PipelineGui.tsx
- website/src/components/operations/args.tsx
- website/src/components/operations/components.tsx
- website/src/components/ui/progress.tsx
- website/src/contexts/PipelineContext.tsx
This PR adds the ability to optimize specific operations and logging specific to the optimizer. The zap button works for map, resolve, and reduce operations. Here's an example for optimizing a map op:
To do:
> feat: add optimizer in the UI

- website/package-lock.json
- website/package.json
- website/src/components/PipelineGui.tsx
Closes #153 (and removes some unnecessary vars)
> fix: switch crypto uuid to regular uuid

- docetl/operations/reduce.py
- tests/basic/test_basic_reduce_resolve.py
Closes #159 by checking if the value is of list-type and converting it to a sorted tuple if so.
> fix: allow reduce_key types to be lists

- docetl/operations/utils.py
Related to  https://github.com/ucbepic/docetl/issues/160
> Sagemaker doesn't yet support tools

- website/src/components/OperationCard.tsx
- website/src/components/operations/args.tsx
Closes #164 by calling `debouncedUpdate` . Also refactored the components/operations/args.tsx---had to set displayName otherwise I was getting many type errors in my IDE for some weird reason.
> fix: save validation and gleaning

- website/src/components/OperationCard.tsx
> Remove unnecessary console log statements

- docs/index.md
> chore: update docs to link to paper

- docetl/builder.py
- docetl/optimizers/join_optimizer.py
- docetl/optimizers/map_optimizer/optimizer.py
- docetl/optimizers/map_optimizer/prompt_generators.py
- docetl/optimizers/reduce_optimizer.py
- docetl/runner.py
- server/app/routes/pipeline.py
- tests/basic/test_optimizer.py
- website/package.json
- website/src/app/api/shouldOptimize/route.ts
- website/src/app/localStorageKeys.ts
- website/src/app/types.ts
- website/src/components/AIChatPanel.tsx
- website/src/components/DatasetView.tsx
- website/src/components/OperationCard.tsx
- website/src/components/Output.tsx
- website/src/components/PipelineGui.tsx
- website/src/components/ResizableDataTable.tsx
- website/src/contexts/PipelineContext.tsx
- website/src/hooks/useOptimizeCheck.ts
- website/src/lib/utils.ts
This PR adds functionality to the optimizer to only compute the `should_optimize` result for an operator. It also adds functionality to the UI to query the should_optimize, and render an indicator if so. Attached is a screenshot of the UI:
The auto-checks are opt-in, and available via pipeline settings.
> feature: add automatic optimization check to the UI (opt in)

- website/src/app/api/constants.ts
- website/src/app/api/shouldOptimize/route.ts
- website/src/components/AIChatPanel.tsx
- website/src/components/ResizableDataTable.tsx
- website/src/hooks/useOptimizeCheck.ts
> fix: ts errors

- docetl/operations/utils.py
If the environment variable is defined then set DOCETL_HOME_DIR to the environment variable, else set it to home directory.
> Change for issue: https://github.com/ucbepic/docetl/issues/180

- website/src/components/OptimizationDialog.tsx
- website/src/components/PipelineGui.tsx
- website/src/components/ResizableDataTable.tsx
> chore: edit copy for the UI

- docetl/operations/utils.py
- docetl/runner.py
> fix sampling in second op onwards

- pyproject.toml
> add python multipart to requirements

- README.md
- docs/playground/index.md
- poetry.lock
- website/src/contexts/WebSocketContext.tsx
> fix: add docs to describe how to set up .env.local

- website/src/mocks/mockData.ts
As title. Gets rid of default operation on initial load.
> fix: change default settings

- server/app/routes/convert.py
- website/src/components/FileExplorer.tsx
- website/src/components/ResizableDataTable.tsx
If the cardinality of the column < 50% of the size of the column, we show a bar chart of the top 10 frequently-occurring values.
> feat: change histograms to be bar charts for categorical columns

- website/src/components/ResizableDataTable.tsx
Could there be something wrong with my local configuration? Why do I always encounter compilation problems... 🤣
> ensure the value is converted to a string when it's not an object

- docetl/operations/code_operations.py
- docetl/operations/utils.py
- docetl/optimizers/map_optimizer/evaluator.py
- docetl/runner.py
- website/src/app/api/utils.ts
- website/src/app/api/writePipelineConfig/route.ts
- website/src/app/localStorageKeys.ts
- website/src/app/playground/page.tsx
- website/src/components/AIChatPanel.tsx
- website/src/components/LLMContextPopover.tsx
- website/src/components/OperationCard.tsx
- website/src/components/OptimizationDialog.tsx
- website/src/components/PipelineGui.tsx
- website/src/components/ResizableDataTable.tsx
- website/src/components/operations/args.tsx
- website/src/components/operations/components.tsx
- website/src/contexts/PipelineContext.tsx
This PR adds the following functionality:
* Global system prompt and persona
* Validation on the UI for the output schema, to make sure that there's at least one key-value pair
* A note in the output schema section of the UI to communicate that this choice affects the user
> feat: have global system prompt and decription

- website/src/components/BookmarksPanel.tsx
- website/src/components/FileExplorer.tsx
- website/src/components/NamespaceDialog.tsx
- website/src/components/Output.tsx
- website/src/contexts/PipelineContext.tsx
Addresses the bug found in #238
> fix: solve infinite rerender bug

- website/src/app/page.tsx
- website/src/app/playground/page.tsx
This PR also adds a warning in /playground if users try to access via mobile.
> chore: optimize website for mobile

- website/src/app/globals.css
- website/src/app/page.tsx
This turns the home page news into a ticker and adds a popover.
> feat: improve website layout

- website/src/app/globals.css
- website/src/app/page.tsx
> fix: website resizing was causing problems with demo

- website/src/app/globals.css
- website/src/app/page.tsx
- website/src/app/playground/page.tsx
> fix: show namespace dialog on load

- website/src/app/api/downloadTutorialDataset/route.ts
- website/src/app/api/utils.ts
- website/src/app/globals.css
- website/src/app/playground/page.tsx
- website/src/app/types.ts
- website/src/components/DatasetView.tsx
- website/src/components/FileExplorer.tsx
- website/src/components/OperationCard.tsx
- website/src/components/OperationHelpButton.tsx
- website/src/components/Output.tsx
- website/src/components/PipelineGui.tsx
- website/src/components/TutorialsDialog.tsx
- website/src/components/operations/components.tsx
- website/src/hooks/useDatasetUpload.ts
- website/src/hooks/useRestorePipeline.ts
- website/src/lib/utils.ts
This PR does two things:
* Addresses much of #248  UI nits
* Adds a sample pipeline of going through 2024's supreme court hearing transcripts
> feat: add sample pipeline for supreme court hearing transcripts

- server/app/routes/convert.py
- vercel.json
- website/src/app/page.tsx
- website/src/app/playground/page.tsx
- website/src/components/AIChatPanel.tsx
- website/src/components/OperationCard.tsx
- website/src/components/PromptImprovementDialog.tsx
- website/vercel.json
we will call the IDE DocWrangler (to align with upcoming paper). This PR changes the name accordingly.
> refactor: updating UI text to docwrangler

- docetl/__init__.py
- docetl/builder.py
- docetl/cli.py
- docetl/operations/equijoin.py
- docetl/operations/map.py
- docetl/optimizers/join_optimizer.py
- docetl/runner.py
- poetry.lock
- pyproject.toml
As title. This PR also adds better error handling and the sampling used in the paper experiments.
> fix: equijoin is out of date

- docetl/containers.py
- docetl/operations/base.py
- docetl/operations/map.py
- docetl/operations/utils/api.py
- docetl/optimizer.py
- website/src/components/TutorialsDialog.tsx
> feat: add new pipeline of customer support tickets

- Makefile
- docetl/containers.py
- docetl/operations/base.py
- docetl/operations/map.py
- docetl/operations/utils/api.py
- docetl/optimizer.py
- website/src/components/TutorialsDialog.tsx
> tests: fix makefile

- website/src/app/playground/page.tsx
- website/src/components/DatasetView.tsx
- website/src/components/FileExplorer.tsx
> fix: performance optimization for dataset loading

- website/src/app/api/utils.ts
- website/src/components/OperationCard.tsx
> fix: allow litellm completion kwargs to work in the FE

- docetl/operations/utils/llm.py
> fix: input context length logic

- docetl/operations/map.py
- docetl/operations/utils/api.py
> Handle DeepSeek R1 distil models: no tool calling and add think column

- .github/workflows/ci.yml
- docetl/__init__.py
- poetry.lock
- pyproject.toml
Closes #297 
Note that we'll have to remove the warning... following https://github.com/BerriAI/litellm/issues/7560
> chore: update packages

- docetl/config_wrapper.py
- docetl/operations/map.py
- docetl/optimizer.py
- docetl/optimizers/utils.py
- docetl/ratelimiter.py
> feat: add rate limiting in optimizer

- README.md
- website/src/app/api/generate/route.ts
- website/src/app/playground/page.tsx
- website/src/components/NaturalLanguagePipelineDialog.tsx
- website/src/components/PipelineGui.tsx
This PR adds a dialog to DocWrangler that allows users to convert natural language task descriptions into a docetl pipeline.
> feat: add NL to pipeline dialog

- docetl/apis/pd_accessors.py
Get rid of .attrs pandas warning
> fix: warning in pd_accessors.py

- website/src/components/utils.ts
> fix: uploading pipeline yaml with complex schemas

- docetl/apis/pd_accessors.py
- docetl/operations/cluster.py
- docetl/operations/equijoin.py
- docetl/operations/link_resolve.py
- docetl/operations/map.py
- docetl/operations/reduce.py
- docetl/operations/resolve.py
- docetl/operations/utils/api.py
- docetl/operations/utils/cache.py
- docs/operators/map.md
- docs/pandas/examples.md
- tests/test_synthetic_output.py
This PR adds an n parameter to output for map operations, which will set the n parameter for the LLM in the chat completion API. This enables synthetic data generation.
> feat: add n parameter to output

- website/src/hooks/useDatasetUpload.ts
> perf: remove client side JSON validation logic

- docetl/cli.py
- docetl/console.py
- docetl/optimizer.py
As title -- thanks to @mygamatoto from Discord!
> fix: don't print locals in rich traceback

- docetl/cli.py
- docetl/console.py
- docetl/optimizer.py
- website/package-lock.json
- website/package.json
- website/src/app/api/chat/route.ts
- website/src/components/AIChatPanel.tsx
- website/src/contexts/PipelineContext.tsx
> feat: add gpt tokenizer to webisite

- docs/python/examples.md
- docs/python/index.md
- mkdocs.yml
> docs: Add python doc examples.

- docetl/operations/utils/api.py
See details in https://docs.snowflake.com/en/user-guide/snowflake-cortex/cortex-llm-rest-api#tools-configuration
> feat: Add support for Snowflake Cortex as an LLM provider

- docs/tutorial-pythonapi.md
- docs/tutorial.md
- mkdocs.yml
> docs: add python api quickstart

- docetl/operations/rank.py
- docs/operators/rank.md
> docs: update documentation for rank op

- docetl/operations/rank.py
- docs/operators/rank.md
> docs: update for rank op

- website/package-lock.json
- website/src/app/playground/page.tsx
- website/src/contexts/PipelineContext.tsx
- website/src/utils/fileOperations.ts
As title.
I also commented out the save / load from .dtl functionality, since it doesn't work well -- addressing part of #342 .
> fix: get rid of namespace infinite loop

- website/package-lock.json
- website/src/app/api/chat/route.ts
- website/src/app/playground/page.tsx
- website/src/contexts/PipelineContext.tsx
- website/src/utils/fileOperations.ts
> nit: update pricing calculation for docwrangler assistant

- website/src/app/showcase/ai-rfi-response-analysis/page.tsx
> nit: add disclaimer to demo

- docetl/operations/rank.py
- website/public/demos/prompts_pipeline.yaml
- website/src/app/showcase/ai-rfi-response-analysis/page.tsx
- website/src/app/showcase/ai-system-prompts-analysis/page.tsx
- website/src/app/showcase/page.tsx
- website/src/components/showcase/system-prompts-explorer.tsx
This PR adds a showcase example that reports on common prompt engineering strategies for AI assistants.
> feat: add prompt example showcase

- docetl/__init__.py
- pyproject.toml
> bump version

- docetl/api.py
- docs/examples/presidential-debate-themes.md
- docs/optimization/python-api.md
- tests/test_api.py
Closes #355 
This PR adds additional kwargs to the python api
> fix: add system prompt and other config vars to python api

- docetl/operations/utils/api.py
- docetl/optimizers/reduce_optimizer.py
> fix: move truncate messages before adding the system prompt

- docetl/operations/base.py
- docetl/operations/cluster.py
- docetl/operations/equijoin.py
- docetl/operations/extract.py
- docetl/operations/link_resolve.py
- docetl/operations/map.py
- docetl/operations/rank.py
- docetl/operations/reduce.py
- docetl/operations/resolve.py
- docetl/runner.py
- docs/concepts/pipelines.md
As title. Also adds to documentation.
> feat: add global bypass cache

- docetl/operations/resolve.py
> fix: truncate documents for embeddings in resolve

- Makefile
- docetl/__init__.py
- docetl/apis/pd_accessors.py
- docetl/operations/resolve.py
- docetl/optimizers/reduce_optimizer.py
Currently `make lint` does not pass on `main`. This PR fixes the errors from `ruff` and also installs the pre-commit hooks when `make install` is run. I ran the pre-commit hooks on the whole project and it fixed a couple other things.
> Have make lint pass

- website/public/demos/contracts_pipeline.yaml
- website/src/app/api/lease-contracts/route.ts
- website/src/app/showcase/lease-contract-red-flags/page.tsx
- website/src/app/showcase/page.tsx
- website/src/components/showcase/lease-contract-explorer.tsx
Adds lease analysis demo for the showcase.
> add new demo

- docetl/operations/sample.py
* Adds ranking and scoring metadata to documents returned by `sample` (`top_embedding` / `top_fts` methods) and `topk` operations.
* Documents now include `{operation_name}_rank` and `{operation_name}_score` fields for better result transparency.
* Updates documentation to explain these new output fields and their usage.
**Implementation**
* **`sample.py`**: Modified `_sample_top_embedding()` and `_sample_top_fts()` to add ranking metadata.
* Adds `{op_name}_rank` field (1-based, where 1 = best match).
* Adds `{op_name}_score` field with similarity/relevance scores.
* For embeddings: cosine similarity score (0–1).
* For FTS: BM25 relevance score.
**Documentation**
* **`sample.md`**: Added “Output Fields” section describing ranking/scoring fields.
* **`topk.md`**
> feat: update topk to also get the rank
