- docetl/operations/map.py
- docs/operators/map.md
- tests/test_basic.py
- Implemented `drop_keys` feature in both `MapOperation` and `ParallelMapOperation` classes
- Updated `syntax_check()` methods to validate `drop_keys` configuration
- Modified `execute()` methods to apply `drop_keys` to the output
- `drop_keys` allows users to specify a list of keys to be removed from the output
- Added appropriate error handling and type checking for `drop_keys` configuration
The new tests cover the drop_keys functionality in both scenarios:
1. When used in conjunction with LLM-based processing
2. When used as a standalone key-dropping operation
> feat: add drop_keys parameter to map operation

- README.md
- docetl/operations/resolve.py
- docetl/runner.py
This PR introduces a prompt to confirm, to the user, that they want to continue executing a resolve operation (if they have not specified any blocking configurations).
> quality of life: show error when trying to execute resolve without blocking

- docetl/operations/equijoin.py
- docetl/operations/reduce.py
- docetl/operations/resolve.py
- docetl/operations/utils.py
- tests/test_ollama.py
This PR closes #21 by removing an unnecessary connection to an openai client.
We also move sklearn imports to not be global (reducing cold start time). 
We also add a test for ollama models (which uses llama3).
> fix: remove openai client call in `utils.py`

- docetl/api.py
- docetl/operations/equijoin.py
- docetl/operations/filter.py
- docetl/operations/map.py
- docetl/operations/reduce.py
- docetl/operations/resolve.py
- docetl/operations/utils.py
- docs/examples/ollama.md
- docs/operators/filter.md
- docs/operators/map.md
- docs/operators/parallel-map.md
- docs/operators/reduce.md
- docs/operators/resolve.md
- mkdocs.yml
- tests/test_map.py
- tests/test_ollama.py
This PR introduces configurable timeouts for operations and adds comprehensive documentation for Ollama integration, enhancing our system's reliability and user guidance. This will close #23.
1. Added support for configurable timeouts in operations
2. Implemented a new `max_retries_per_timeout` parameter (default: 2)
3. Created a new test in `test_map.py` to verify the timeout functionality
4. Added documentation for Ollama integration with timeout examples
- Operations now accept a `timeout` parameter in their configuration
- If a timeout occurs, the operation will retry up to `max_retries_per_timeout` times
- `max_retries_per_timeout`: Controls the number of retry attempts after a timeout (default: 2)
- Added a new test case in `test_map.py` to ensure proper functionality of the timeout …
> Add Configurable Timeouts for Operations and Ollama Integration Documentation

- docetl/operations/utils.py
This PR checks if the model is an ollama model and calls `ast.literal_eval` on the outputs if they are strings.
Note that this is totally a hack to solve the issue that the models are not good at coming up with structured outputs.
> fix: manually try to parse ollama outputs, even if it is not valid json

- docetl/__init__.py
- docetl/operations/utils.py
- pyproject.toml
If a user tries to use an LLM that doesnt support function calling, the operation won't work. We should raise an error for this.
> fix: add error messages if model doesnt support tool calling

- docetl/operations/base.py
- docetl/operations/equijoin.py
- docetl/operations/filter.py
- docetl/operations/map.py
- docetl/operations/reduce.py
- docetl/operations/resolve.py
- docetl/operations/utils.py
- docetl/runner.py
- poetry.lock
- tests/test_map.py
- tests/test_ollama.py
This PR closes #29. It also introduces a `manually_fix_errors` parameter in the config, but I don't think I'll expose it in the docs until the UI is out later this week.
> feat: show better progress bars for operations

- poetry.lock
**Summary**
This pull request introduces batching support to map operations as described in issue #7, with the aim of significantly enhancing performance and reducing costs when processing small documents. Key updates include new batching parameters, implementation of batching logic, configuration enhancements, expanded testing, and documentation improvements. Additionally, Pydantic models have been introduced in `schemas.py` to simplify and streamline validation logic.
---
**Main Changes**
1. **Batching Support in Map Operations**
- **New Parameters**: Added `batch_size` and `clustering_method` to the map operation interface to enable batching functionality.
- **Batching Logic**: Implemented logic to group documents based on the specified batch size and clustering method, optimizing the …
> Add batching support to map operations with configurable parameters

- docetl/api.py
- docetl/builder.py
- docetl/dataset.py
- docetl/operations/utils.py
- docetl/parsing_tools.py
- docetl/runner.py
- docs/examples/custom-parsing.md
- docs/installation.md
- poetry.lock
- pyproject.toml
- tests/test_parsing_tools.py
This PR introduces a new parsing tool, `azure_di_read`, which leverages Azure's Document Intelligence service to extract text from various document types, including PDFs, images, and scanned documents.
- Extracts text from documents using Azure Form Recognizer
- Supports both local files and URLs
- Configurable options for including line numbers, handwritten text, font styles, and selection marks
- Option to return each page as a separate document or combine all pages into a single output
To use this new tool, users need to:
1. Set up Azure Document Intelligence service and obtain API credentials
2. Set environment variables for `DOCUMENTINTELLIGENCE_API_KEY` and `DOCUMENTINTELLIGENCE_ENDPOINT`
3. Configure the parsing tool in their DocETL pipeline configuration
Example configuration: …
> Add Azure Document Intelligence Read Tool

- Makefile
- docetl/cli.py
- docetl/operations/utils.py
- docetl/schemas.py
This PR closes #37 and rolls in another change to the tool schema so llama models work better with structured output.
> fix: read .env from the user's cwd and change tool schema so ollama llama models work better

- docetl/operations/utils.py
diskcache isn't 100% threadsafe and can under certain conditions end up unable to open the sqlite database with an `OperationalError`. This only happens if threads do not close their cache when not using it. Closing the cache and reopening it is slightly slower, but fixes this problem. Solution copied from the documentation of `diskcache`.
> Bugfix for sqlite3 operation error in cache

- docetl/operations/reduce.py
- docs/tutorial.md
This PR closes #41 by making sure the reduce prompt template follows the expected pattern (referencing `inputs`) and updates the reduce op error messages to be more thorough.
> fix: template in tutorial.md

- docetl/optimizers/join_optimizer.py
- docetl/utils.py
Fixes #56 -- where pipelines fail if using an azure gpt model, since `azure/` is not a prefix one can search for in the tiktoken encoding map.
> fix: default to gpt 4o tokenizer

- docetl/operations/resolve.py
- docetl/operations/utils.py
- docs/best-practices.md
- docs/tutorial.md
- poetry.lock
- tests/basic/test_basic_map.py
> feat: don't use tool calling for ollama/OSS models if the output schema is just one param

- Makefile
- docetl/runner.py
- tests/test_runner_caching.py
Closes #49 
This PR introduces a new caching mechanism based on operation hashes, allowing for more efficient pipeline execution by skipping previously completed operations when their configurations haven't changed.
- Added `step_op_hashes` to `DSLRunner` to store hashes of operation configurations
- Implemented hashing logic for each step _and_ operation in the pipeline
- Modified `execute_step` to check for existing cached results before running operations
- Added `_load_from_checkpoint_if_exists` method to load cached data if available
- Updated `_save_checkpoint` to save operation hashes along with data
- Added logic to save and load `.docetl_intermediate_config.json` for persistent caching
- Operation hashes are calculated using SHA256 on the JSON representation of operation …
> Add Operation Hash and Caching Functionality

- docetl/operations/utils.py
- tests/test_azure_rl.py
This is a very hacky fix, but this PR adds exponential backoff logic for `call_llm` whenever there is a RateLimitError. It does it until the operation fully completes. It does not address #46, but at least it makes docetl usable...
> (partial) fix: add exponential backoff for rate limit errors

- docetl/operations/base.py
- docetl/operations/utils.py
- tests/basic/test_basic_map.py
The `gleaning` feature wasn't working, so this PR removes an extraneous argument to a function call as a fix. Also adds a test.
> fix: enable gleaning llm calls to work

- docetl/dataset.py
- docetl/parsing_tools.py
- docs/operators/split.md
Closes https://github.com/ucbepic/docetl/issues/72
This should be backwards compatible with existing yaml. It also supports the following extended yaml format:
```
datasets:
name:
type: file
source: local
path: "file.json"
parsing:
- function: function_name
param_name1: value1
param_name2: value2
...
param_nameN: valueN
```
`input_key` and `output_key` are supported for all previously existing parsers (and are just normal parameters to them), but might not be supported by any particular new parser. In fact, the llama-index based ones do not support an `output_key`, but instead places the output in the two fields `text` and `metadata`.
For the existing functions that do take `input_key` and `output_key`, they are both optional and both have default value `"text"`.
> Parsers can now return any number of fields, and can access the whole item

- docetl/api.py
- docetl/operations/map.py
- docetl/operations/reduce.py
- docetl/operations/split.py
- docetl/operations/utils.py
- docetl/optimizers/reduce_optimizer.py
- docetl/utils.py
- docs/concepts/operators.md
- docs/examples/custom-parsing.md
- docs/examples/rate-limiting.md
- mkdocs.yml
- tests/basic/test_pipeline_with_parsing.py
- tests/test_api.py
- tests/test_validation.py
This PR also adds documentation.
> Merge staging to main (after parsers refactor)

- docetl/api.py
- docetl/operations/cluster.py
- docetl/operations/map.py
- docetl/operations/reduce.py
- docetl/operations/split.py
- docetl/operations/utils.py
- docetl/optimizers/reduce_optimizer.py
- docetl/utils.py
- docs/api-reference/operations.md
- docs/concepts/operators.md
- docs/examples/custom-parsing.md
- docs/examples/rate-limiting.md
- docs/operators/cluster.md
- docs/operators/filter.md
- docs/operators/gather.md
- docs/operators/map.md
- docs/operators/parallel-map.md
- docs/operators/reduce.md
- docs/operators/resolve.md
- docs/operators/split.md
- docs/operators/unnest.md
- mkdocs.yml
- pyproject.toml
- tests/basic/test_cluster.py
- tests/basic/test_pipeline_with_parsing.py
- tests/test_api.py
- tests/test_validation.py
> Merge staging to main (after adding cluster operator)

- docetl/operations/cluster.py
Added an optional option `collapse` to clustering operation. If present, it should be set to a value between 0 and 1. The closer to 1, the shallower the tree of clusters, and the more children each cluster will have. At 0, it is virtually the same as when not present: Each cluster has exactly 2 children.
Note: The `summary_prompt` template now takes a `inputs` list parameter, instead of a `left` and `right`.
If set to a suitably high number, this greatly improves the cost of the clustering. Whether the resulting flatter tree is desirable is application dependent.
> Added collapse option to clustering

- docetl/optimizers/join_optimizer.py
This PR edits one of the join optimizers' agent prompt to instruct that the LLM should return a jinja template.
> fix: edit agent for synth resolve task

- README.md
- docetl/api.py
- docetl/schemas.py
- docs/operators/cluster.md
- tests/test_runner_caching.py
allows user to use clusterop and sampleop in api
> fix: update python api with cluster & sample ops

- docetl/operations/map.py
- docetl/operations/resolve.py
The `RichLoopBar` in `Map` and `Resolve` gets updated beyond the number of expected items. `for i in pbar` should suffice for updating it, `pbar.update(i)` can be removed.
> Fix Resolve and Map progress bars

- server/app/main.py
* fastapi uses the environment variables in. env under the current directory
> chore, load envs from current directory

- website/src/components/BookmarkableText.tsx
- website/src/components/ResizableDataTable.tsx
```bash
$ node --version
v18.20.4
$ npm --version
10.7.0
```
```bash
./src/components/Output.tsx:254:43
Type error: Type '{ children: Element; source: string; className: string; }' is not assignable to type 'IntrinsicAttributes & BookmarkableTextProps'.
Property 'className' does not exist on type 'IntrinsicAttributes & BookmarkableTextProps'.
252 |         </div>
253 |       ) : outputs.length > 0 ? (
> 254 |         <BookmarkableText source="output" className="h-full">
|                                           ^
255 |           <ResizableDataTable
256 |             data={outputs}
257 |             columns={columns}
```
```bash
./src/components/ResizableDataTable.tsx:240:5
Type error: Object literal may only specify known properties, and 'onColumnSizingStart' does not exist in type …
```
> hotfix: an error occurred when running make run-ui

- website/src/components/AIChatPanel.tsx
> feat: provide defaults in the UI chat

- docetl/operations/cluster.py
- docetl/operations/equijoin.py
- docetl/operations/link_resolve.py
- docetl/operations/map.py
- docetl/operations/reduce.py
- docetl/operations/resolve.py
- docetl/operations/utils.py
- docs/concepts/operators.md
- docs/operators/cluster.md
- docs/operators/map.md
- docs/operators/parallel-map.md
- docs/operators/reduce.md
- docs/operators/resolve.md
- tests/basic/test_basic_map.py
Closes #161. This also adds instructions to the documentation.
Now for every operation, the user can pass in a `litellm_completion_kwargs` param, which will be a dictionary. For example:
```yaml
- name: extract_insights
type: map
model: gpt-4o-mini
litellm_completion_kwargs:
max_tokens: 500          # limit response length
temperature: 0.7         # control randomness
top_p: 0.9              # nucleus sampling parameter
prompt: |
Analyze the following user interaction log:
{{ input.log }}
Extract 2-3 main insights from this log, each being 1-2 words, to help inform future product development. Consider any difficulties or pain points the user may have had. Also provide 1-2 supporting actions for each insight.
Return the results as a list of dictionaries, each containing 'insight' and …
```
> fix: allow user to pass in litellm completion kwargs

- website/package-lock.json
- website/package.json
- website/src/app/types.ts
- website/src/components/AIChatPanel.tsx
- website/src/components/Output.tsx
- website/src/components/PipelineGui.tsx
- website/src/components/ResizableDataTable.tsx
- website/src/components/operations/args.tsx
- website/src/components/operations/components.tsx
Closes #169. Attaching screenshots here.
A code map operation:
Add operation dropdown
The PR also adds support for sorting columns in the output table.
> feat: add code operations to the ui (#169)

- website/src/components/operations/components.tsx
```typescript
Type error: Import declaration conflicts with local declaration of 'Operation'.
1 | import React from "react";
> 2 | import { Operation, SchemaItem } from "'app/types"' (see below for file content);
|          ^
3 | import { OutputSchema, PromptInput, CodeInput } from "./args";
4 | import { useMemo } from "react";
5 | import { Input } from "'components/ui/input"' (see below for file content);
make: *** [Makefile:42: run-ui] Error 1
```
> hotfix: Import declaration conflicts with local declaration of 'Operation'.

- docetl/operations/code_operations.py
* The default is os.cpu_count().
> Receive a customized parameter to specify the number of concurrent running threads for the code_* operations.

- website/src/app/api/writePipelineConfig/route.ts
I suspect the bug around running pipelines is due to the fact that Intermediates were not created
A renaming of the default pipeline to `DEBATE_ANALYSIS2` should validate 
Feel free to close if I am mistaken
> Intermediates fix

- poetry.lock
- pyproject.toml
- server/app/routes/convert.py
- website/src/app/api/convertDocuments/route.ts
- website/src/components/FileExplorer.tsx
- website/src/mocks/mockData.ts
This PR allows a user to specify their azure doc intelligence credentials in the UI, to upload their pdfs. Screenshot below.
> feat: Add azure doc intelligence to PDF upload in the UI

- README.md
- docetl/operations/map.py
- docetl/operations/reduce.py
- docetl/operations/resolve.py
- docetl/optimizers/join_optimizer.py
- website/src/app/api/utils.ts
- website/src/components/Output.tsx
- website/src/components/ResizableDataTable.tsx
Now, each row in the output table has an "eye" icon:
I've accommodated map, parallel map, filter, reduce, resolve. Need to test non-map operations in the UI.
> feat: add basic llm call observability to the UI

- docetl/operations/utils.py
- docs/concepts/operators.md
Fixes #95 by updating cache naming for more conventional naming structure as well as the documentation in operators.md. 
Expected risk: minimal seems like all usages of the cache just call the instance in utils.py
> Fix cache naming

- poetry.lock
- server/app/routes/convert.py
- tests/test_runner_caching.py
- website/package-lock.json
- website/package.json
- website/src/app/api/convertDocuments/route.ts
- website/src/app/globals.css
- website/src/app/page.tsx
- website/src/app/playground/page.tsx
- website/src/components/AnsiRenderer.tsx
- website/src/components/BookmarksPanel.tsx
- website/src/components/ColumnDialog.tsx
- website/src/components/DatasetView.tsx
- website/src/components/FileExplorer.tsx
- website/src/components/NamespaceDialog.tsx
- website/src/components/OperationCard.tsx
- website/src/components/OptimizationDialog.tsx
- website/src/components/PipelineGui.tsx
- website/src/components/PromptImprovementDialog.tsx
- website/src/components/ui/dialog.tsx
- website/src/components/ui/menubar.tsx
- website/src/components/ui/radio-group.tsx
- website/src/components/ui/toast.tsx
- website/src/components/utils.ts
- website/src/contexts/ThemeContext.tsx
- website/src/hooks/use-toast.ts
- website/src/lib/utils.ts
As title. This PR also adds themes (all light). Here's an example of the majestic theme:
> feat: clean up UI to look a bit more consistent and smooth

- .gitignore
- docetl/operations/utils/validation.py
- docs/concepts/operators.md
- docs/concepts/schemas.md
- tests/basic/test_basic_map.py
> added enum support

- docetl/builder.py
- docetl/operations/base.py
- docetl/operations/map.py
- docetl/optimizers/map_optimizer/config_generators.py
- docetl/optimizers/map_optimizer/evaluator.py
- docetl/optimizers/map_optimizer/optimizer.py
- docetl/optimizers/map_optimizer/plan_generators.py
- docetl/runner.py
- docs/operators/map.md
For our model cascades experiments (separate project), sometimes we run into errors like content warnings or repetitive words in prompt (400 error), which terminates the program. We should allow users to skip these.
> chore: add param to skip LLM calls when they fail

- server/app/routes/convert.py
- website/src/app/api/convertDocuments/route.ts
- website/src/components/FileExplorer.tsx
- Bugfixes and compatibility: Fixed issues with docling-serve return values and URL backslashes.
- Backend request handling: Changed to backend for sending requests.
- Markdown image format: Removed base64 images from Markdown.
- UI adjustments: Reduced file selection component height and ensured processing methods display on one line.
> Fixed bugs, improved compatibility, adjusted backend, and enhanced UI

- server/app/routes/convert.py
- website/src/app/api/convertDocuments/route.ts
- website/src/components/FileExplorer.tsx
As title, for #253 
Currently I don't have a docling server set up with the docling-serve spec. So I'll wait to try it; possibly @plpycoin can test whether this PR works? Or I can look into it sometime next week to test.
> feat: add ability for user to specify their docling server

- docetl/containers.py
- docetl/optimizers/join_optimizer.py
This PR adds the following:
- ability to set sample sizes for both left and right datasets for optimizing equijoins
- limit retries in sampling
- some (basic) prompt engineering
- not exposing the synthesized keys to the agent creating blocking rules
> feat: quality of life improvements for equijoin optimizer

- docetl/operations/utils/api.py
- docetl/utils.py
- docs/operators/map.md
- docs/operators/reduce.md
- docs/operators/resolve.md
- tests/basic/test_basic_map.py
This PR does 2 things:
- add verbose param to print LLM input and output
- add bypass_cache to docs
> docs: add verbose param

- website/src/app/api/utils.ts
- website/src/app/types.ts
- website/src/components/operations/args.tsx
- website/src/components/utils.ts
- website/src/hooks/useRestorePipeline.ts
> feat: add enum to UI

- docetl/operations/utils/api.py
> Detect case variations: DeepSeek-R1 vs deepseek-r1

- .env.sample
- docker-compose.yml
- server/app/main.py
- website/package-lock.json
- website/package.json
This pull request introduces docker-compose support by adding necessary port mappings in .env.sample and a new docker-compose.yml file to run the services. Please review the changes and let me know if further adjustments are needed.
> 🚀 feat: add docker-compose support

- docetl/api.py
- docetl/cli.py
- docetl/config_wrapper.py
- docetl/operations/map.py
- docetl/operations/utils/api.py
- docetl/optimizer.py
- docetl/optimizers/utils.py
- docetl/runner.py
- server/app/routes/pipeline.py
- website/src/app/api/getPipelineConfig/route.ts
- website/src/app/api/utils.ts
- website/src/app/api/writePipelineConfig/route.ts
- website/src/components/OperationCard.tsx
- website/src/components/PipelineGui.tsx
Closes #305 
To do (in future PR):
* support graceful interrupts for the optimizer as well as (#222 )
> feat: allow optimizer model to be any litellm supported model

- website/src/components/operations/components.tsx
This PR provides the option in DocWrangler to pass a URL key. In response to #310.
> feat: add PDF url key option to DocWrangler for Map operation

- docetl/operations/map.py
- docetl/runner.py
- docs/operators/map.md
- tests/basic/test_basic_map.py
Addresses #321 with a new flag for just for the map operation. To keep the change minimal for a single PR, there is nothing here that also reuses the already processed batches.
I implemented a method in the runner that could be an opt-in for other Ops too. Unsure though how generic it is.
> feat: add flag to stream map operation outputs to disk

- docetl/operations/map.py
- website/src/components/FileExplorer.tsx
In DocWrangler, now every upload of a PDF should stores the full path of a file (in the _file_path key), and it can be referenced in the pdf_url_key in map and filter operations if users want to use claude or gemini.
> feat: add _file_path to each document when uploading the dataset

- docetl/config_wrapper.py
- docetl/operations/map.py
- docetl/operations/sample.py
- docetl/operations/utils/api.py
- docetl/operations/utils/llm.py
- docs/examples/rate-limiting.md
- website/src/app/api/getInputOutput/route.ts
- website/src/app/api/getPipelineConfig/route.ts
- website/src/app/api/utils.ts
- website/src/app/api/writePipelineConfig/route.ts
- website/src/app/localStorageKeys.ts
- website/src/components/OperationCard.tsx
- website/src/components/PipelineGui.tsx
- website/src/components/PipelineSettings.tsx
- website/src/contexts/PipelineContext.tsx
We got a request from the community to add support for setting rate limits in DocWrangler. This PR allows users to set other pipeline settings like rate limits, and adds support for token per minute (TPM) rate limits. We also added a TPM example to the documentation.
There are three types of rate limits: embedding_call, llm_call (e.g., RPM), and llm_tokens (e.g., TPM).
> feat: add TPM rate limits & pipeline settings to DocWrangler

- docetl/operations/rank.py
- docs/operators/rank.md
- website/src/app/types.ts
- website/src/components/NaturalLanguagePipelineDialog.tsx
- website/src/components/PipelineGui.tsx
- website/src/components/TutorialsDialog.tsx
- website/src/components/operations/args.tsx
- website/src/components/operations/components.tsx
- website/src/hooks/useRestorePipeline.ts
This PR does the following:
- Adds a rank operation card to DocWrangler
- Edits the rank op documentation in DocETL
- Adds tqdm progress bars to the rank operation in DocETL 
Here is a screenshot:
> feat: add rank operation card in docwrangler

- docetl/operations/utils/api.py
Somehow it is not working this week, maybe because of a new release from litellm.
> Use hasattr when checking `response.choices[index].message`

- docetl/operations/utils/api.py
We need to add this extra param so it will not fail when upgrading litellm to 1.67.4
> Add "allowed_openai_params" argument for Snowflake model

- docetl/operations/utils/api.py
- docs/concepts/pipelines.md
This allows folks to point DocETL to their own hosted models very easily (as long as they have an openai api compatible llm).
> feat: adding `api_base` to yaml

- docetl/operations/extract.py
- docetl/operations/map.py
- docetl/operations/rank.py
- docetl/operations/utils/api.py
- docs/operators/map.md
- tests/basic/test_basic_map.py
- tests/test_runner_caching.py
Problem: When using map operations for classification or scoring tasks, LLMs often produce inconsistent results across documents because they process each document in isolation without context about the full dataset distribution. For example, what gets classified as "medium priority" early in processing might be classified as "high priority" later when the LLM encounters more severe examples.
Solution: Added calibration support that samples a subset of documents, processes them first, then uses those results to generate reference anchors that get appended to the original prompt. This gives the LLM concrete examples from the actual dataset to calibrate against.
The implementation is intentionally simple - just two new parameters:
- calibrate: bool (default false)
- num_calibration_docs: …
> feat: Add calibration support to map operations for improved consistency

- docetl/optimizers/reduce_optimizer.py
As title. Fixes the following bug (found on Discord)
```
21:54:42 - LiteLLM:INFO: utils.py:1120 - Wrapper: Completed Call, calling success_handler
INFO     Wrapper: Completed Call, calling success_handler                                                                             utils.py:1120
Error occurred:
Traceback (most recent call last):
File "/app/server/app/routes/pipeline.py", line 244, in websocket_run_pipeline
result = await pipeline_task
^^^^^^^^^^^^^^^^^^^
File "/app/server/app/routes/pipeline.py", line 189, in run_pipeline
return await asyncio.to_thread(runner.optimize, return_pipeline=False)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
return await loop.run_in_executor(None, …
```
> fix: create join optimizer object correctly

- docetl/operations/utils/api.py
Fixes a couple of bugs
- adds `name` attribute to synthesized resolve
- moves `truncate_messages` to be before the system prompt addition in llm call utils
> fix: reduce optimizer bugs

- tests/basic/test_basic_filter_split_gather.py
- tests/basic/test_basic_map.py
- tests/basic/test_basic_parallel_map.py
- tests/basic/test_basic_reduce_resolve.py
- tests/basic/test_cluster_and_sample.py
- tests/conftest.py
- tests/ranking/test_rank.py
- tests/ranking/test_rank_budget.py
- tests/test_azure_rl.py
- tests/test_eugene.py
- tests/test_reduce_scale.py
- tests/test_reduce_value_sampling.py
- tests/test_resolve_auto_batch.py
- tests/test_split.py
- tests/test_synth_gather.py
- tests/test_synthetic_output.py
- tests/test_validation.py
Refactor pytest fixtures and test organization to improve maintainability and readability.
The `conftest.py` file was significantly reduced (by 55%) by moving test-specific fixtures to their respective test files, removing unused fixtures, and relocating a misplaced test function. Additionally, the `api_wrapper` fixture was renamed to `runner` for better semantic clarity, with all references updated across the test suite. These changes centralize truly shared fixtures and localize single-use ones, making the test suite leaner and easier to navigate.
> Clean up and reorganize pytest tests

- docetl/apis/pd_accessors.py
- docs/pandas/examples.md
- docs/pandas/index.md
- docs/pandas/operations.md
- docs/tutorial-pythonapi.md
- tests/test_pandas_accessors.py
Add `split`, `gather`, and `unnest` operators to the pandas API to expand supported semantic operations (fixes #296).
> Add operators to pandas API

- docetl/operations/base.py
- docetl/operations/utils/progress.py
- docetl/schemas.py
- docetl/utils.py
Depends on #389, so does not make sense to review until that is merged in. This PR makes the following improvements to `docetl/utils.py`:
1. Adds type annotations to fix `mypy` issues in this file.
2. Removes the duplicate `classproperty` definition in `docetl/operations/base.py`
> Clean up utility code

- Makefile
- docetl/operations/sample.py
- docetl/operations/topk.py
- docs/operators/sample.md
- docs/operators/topk.md
- mkdocs.yml
- pyproject.toml
- tests/basic/test_sample_top_methods.py
- tests/basic/test_topk.py
- uv.lock
This PR introduces a topk operation for document retrieval, extending the existing sample operation with semantic similarity and full-text search capabilities. The implementation supports both embedding-based retrieval and FTS via BM25, with optional stratified sampling.
Added a new topk operation that provides a cleaner interface for retrieval use cases, wrapping the sample operation's new top_embedding and top_fts methods. The operation supports retrieving items by semantic similarity, full-text search, or LLM-based comparison.
The sample operation was extended to handle these retrieval methods while maintaining backward compatibility. Both operations now support stratified retrieval across multiple keys and flexible k-selection using counts or percentages.
- Run existing test suite to …
> feat: add topk implementation

- website/src/components/TutorialsDialog.tsx
The output schema has just three fields, but the formatting instructions and the example in the prompt include extra fields. As these extra fields are not used downstream in the pipeline, this patch removes them from the prompt.
> Fix mismatch between prompt and output schema
